### ISSUE TITLE
Trace does not actually lock

### ISSUE THREAD

**Issue by HansKristian-Work** [GPUOpen-LibrariesAndSDKs/Cauldron#10]
While debugging the SSSR sample I stumbled upon a lock allocated on stack:
https://github.com/GPUOpen-LibrariesAndSDKs/Cauldron/blob/master/src/common/Misc/Misc.cpp#L83

**Comment by aguaviva** [comment]
You are right! We are not using MT now so it's not a big deal but we'll fix it in the next release.

**Comment by aguaviva** [comment]
fixed in v1.2
