### ISSUE TITLE
Block compressed dds

### ISSUE THREAD

**Issue by manaskulkarni786** [GPUOpen-LibrariesAndSDKs/Cauldron#11]
Is loading of BC formats supported? I have tried with a few dds files and it always shows garbage data in both VK and D3D12
Attached a BC3 version of Default_albedo.png from the Damaged Helmet GLTF in Cauldron Media repo and screenshot from the app.
![Cauldron](https://user-images.githubusercontent.com/30538315/85431162-c56df780-b59e-11ea-9ed1-945af4b4a24a.png)

[Default_albedo.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Cauldron/files/4820715/Default_albedo.zip)

Thank you

**Comment by aguaviva** [comment]
You are right. The good news is that the fix is already implemented and
will be available in the next release.

**Comment by aguaviva** [comment]
fixed in v1.2
