### ISSUE TITLE
Camera position is not correctly updated in Camera::UpdateCameraPolar()

### ISSUE THREAD

**Issue by sonehiro** [GPUOpen-LibrariesAndSDKs/Cauldron#13]
Hello.

I found that I was not able to update camera position when using `Camera::UpdateCameraPolar()`.  
I think `eyePos` should be used instead of `m_eyePos` in this line, is this correct?  
https://github.com/GPUOpen-LibrariesAndSDKs/Cauldron/blob/master/src/common/Misc/Camera.cpp#L122

**Comment by aguaviva** [comment]
Hi sonehiro, are you using v1.3?

**Comment by sonehiro** [comment]
Hi aguaviva, no I was using v1.2 when I found this problem.
I have updated to v1.3 and now it works correctly.
I am sorry I did not notice that it is already fixed, but thank you for responding.
