### ISSUE TITLE
DivideRoundingUp compile error

### ISSUE THREAD

**Issue by kittikun** [GPUOpen-LibrariesAndSDKs/Cauldron#14]
```
template<typename T> inline T DivideRoundingUp(T a, T b)
{
    return (x + y - (T)1) / y;
}
```
You probably wanted to use x and y so the definition should be 
`template<typename T> inline T DivideRoundingUp(T x, T y)`

**Comment by rys** [comment]
Fixed in Cauldron v1.4, sorry it took so long to get round to clarifying that.
