### ISSUE TITLE
UploadHeap::Suballocate assert(uSize...) will not fire at heap over size allocation...

### ISSUE THREAD

**Issue by ChemistAion** [GPUOpen-LibrariesAndSDKs/Cauldron#15]
I catch this one, here:
https://github.com/GPUOpen-LibrariesAndSDKs/Cauldron/blob/b3a4f62bf79034240b979d575e67ee51790ab435/src/DX12/base/UploadHeap.cpp#L94

It should be reversed, i.e.: `assert(uSize < (size_t)(m_pDataEnd - m_pDataBegin));`
Perhaps, additional - similar assert for `AlignUp()` case also...

**Comment by ChemistAion** [comment]
@rys Could you please take a look on this?

**Comment by rys** [comment]
Yep, we'll fix for the next release. Thanks again!

**Comment by ChemistAion** [comment]
Perfect! So, I will leave this "Open" for now.
