### ISSUE TITLE
SwapChain::WaitForSwapChain wrong "CPU wait for fence" setup

### ISSUE THREAD

**Issue by ChemistAion** [GPUOpen-LibrariesAndSDKs/Cauldron#16]
I catch next one, here:
https://github.com/GPUOpen-LibrariesAndSDKs/Cauldron/blob/b3a4f62bf79034240b979d575e67ee51790ab435/src/DX12/base/SwapChain.cpp#L163

For now, this fires only once at the very first round.
It should wait for previous `backBuffferIndex` - it works now only due to engine happy-scenario ...

Perhaps: `m_swapChainFence.CpuWaitForFence(backBuffferIndex == 0 ? m_BackBufferCount : backBuffferIndex - 1);`

**Comment by ChemistAion** [comment]
@rys Could you please take a look on this?

**Comment by rys** [comment]
Yep, we'll fix this in the next release. Thanks for reporting, and we'll do a better job keeping on top of issues here in the future.

**Comment by ChemistAion** [comment]
Perfect! So, I will leave this "Open" for now.

**Comment by ChemistAion** [comment]
ehh... we should wait for _oldest_ fence - instead of _previous/last_ one - as I proposed in first comment.
This would be: `m_swapChainFence.CpuWaitForFence(backBuffferIndex == m_BackBufferCount - 1 ? 0 : backBuffferIndex + 1);`

**Comment by ChemistAion** [comment]
@rys: it was perfectly fine since very begining - I did not read `m_swapChainFence.CpuWaitForFence(N)` it waits `N` number of frames, not for the frame number...
