### ISSUE TITLE
How to tell actual RAM usage?

### ISSUE THREAD

**Issue by ompadu** [GPUOpen-LibrariesAndSDKs/Cauldron#22]
Given that Cauldron allocates large swaths of memory to use as a buffer, how can one tell the how much actual memory is being used? 

Can the pre-allocation system be disabled? Or is there any chance that the system metrics window will contain memory usage information too in the future?

Thank you

**Comment by rys** [comment]
Sadly we don't have any plans to add memory usage metrics directly into the Cauldron UI, or to change the memory allocation behaviour. There are vendor tools out there that can help you trace and analyse memory usage however and we recommend looking at those to get more insight into GPU memory usage in general ([Nsight Graphics](https://developer.nvidia.com/nsight-graphics), [Radeon Memory Visualizer](https://gpuopen.com/rmv/) and [Intel GPA](https://www.intel.com/content/www/us/en/developer/tools/graphics-performance-analyzers/overview.html) in particular).
